version: '3.4'

services:
  platformservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  commandsservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

